version: '3.5'

services:
  db:
    image: postgres
    restart: always
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
  redis:
    image: redis
    command: redis-server
    volumes:
      - 'redis:/data'
  web:
    build: .
    env_file: .env
    tty: true
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/interviewapp
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    environment:
      - REDIS_URL_CACHING=redis://redis:6379/0
      - DATABASE_HOST=db
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=password
  sidekiq:
    build: .
    env_file: .env
    command: bundle exec sidekiq -c 5 -q default -q mailers
    volumes:
      - .:/interviewapp
    depends_on:
      - db
      - redis
    environment:
      - REDIS_URL=redis://redis:6379
      - REDIS_URL_CACHING=redis://redis:6379/0
      - DATABASE_HOST=db
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=password

volumes:
  redis:
  postgres:
